### Admin Login
POST {{base-url}}/users/login/
Content-Type: application/json

{
  "name": "admin",
  "password": "adminSecret"
}
> {% client.global.set("auth_token", response.body.token); %}

### Create value target structure
POST {{base-url}}/structures/create
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Corporate Value Target",
  "fields": [
    {
      "name": "Norm Target Name",
      "type": "string"
    },
    {
      "name": "Norm Target Description",
      "type": "string"
    },
    {
      "name": "Norm Target Assessor",
      "type": "string"
    },
    {
      "name": "Smart Norm Target",
      "type": "string"
    }
  ]
}
> {% client.global.set("targetStructureID", response.body._id); %}

### Create value norm structure
POST {{base-url}}/structures/create
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Corporate Value Norm",
  "fields": [
    {
      "name": "Title",
      "type": "string"
    },
    {
      "name": "Description",
      "type": "string"
    },
    {
      "name": "Targets",
      "type": "array",
      "items": "{{targetStructureID}}"
    }
  ]
}
> {% client.global.set("normStructureID", response.body._id); %}


### Create value activity structure
POST {{base-url}}/structures/create
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Corporate Value Activity",
  "fields": [
    {
      "name": "Activity Title",
      "type": "string"
    },
    {
      "name": "Activity Description",
      "type": "string"
    },
    {
      "name": "Activity Responsible",
      "type": "string"
    },
    {
      "name": "Value Norms",
      "type": "array",
      "items": "{{normStructureID}}"
    }
  ]
}
> {% client.global.set("activityStructureID", response.body._id); %}

### Create value goal structure
POST {{base-url}}/structures/create
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Corporate Value Goal",
  "fields": [
    {
      "name": "Goal Title",
      "type": "string"
    },
    {
      "name": "Goal Description",
      "type": "string"
    },
    {
      "name": "Goal Responsible",
      "type": "string"
    },
    {
      "name": "Value Activities",
      "type": "array",
      "items": "{{activityStructureID}}"
    }
  ]
}
> {% client.global.set("goalStructureID", response.body._id); %}

### Create value issue structure
POST {{base-url}}/structures/create
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Corporate Value Issue",
  "fields": [
    {
      "name": "Issue Title",
      "type": "string"
    },
    {
      "name": "Issue Description",
      "type": "string"
    },
    {
      "name": "Value Goals",
      "type": "array",
      "items": "{{goalStructureID}}"
    }
  ]
}
> {% client.global.set("issueStructureID", response.body._id); %}

### Create value structure
POST {{base-url}}/structures/create
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Corporate Value",
  "fields": [
    {
      "name": "Value Title",
      "type": "string"
    },
    {
      "name": "Value Description",
      "type": "string"
    },
    {
      "name": "Value Issues",
      "type": "array",
      "items": "{{issueStructureID}}"
    }
  ]
}